--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KienMCVN/SellExpUI
build-by-default: true
branches:
- main
projects:
  SellExpUI:
    path: ""
    libs:
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy 
      version: ^3.0.2
...
